### ISSUE TITLE
need to wait for other blockers

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-metadetect-task#5]
I've realized that it is basically pointless to work on the coadding code here until we first update `descwl_coadd` to work on DM exposure objects rather than the current outputs from the sims.

So the blockers are
- [x] need the sims to produce stack exposures, stack wcs and the bbox that comes in the `skyInfo`
- [x] need the `descwl_coadd` code to work from these rather than the sim outputs
- [x] We need to do full runs of the sim tests after we do this update to make sure nothing breaks

**Comment by esheldon** [comment]
this is a significant amount of work, probably a few weeks

**Comment by arunkannawadi** [comment]
Let me know if I can help. It's probably easier for you to work, but I'd like to learn how your code work using this as an opportunity.
